[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
                "@openzepplin/=lib/openzepplin-contracts" , 
                "@ERC721A-Upgradeable/=lib/ERC721A-Upgradeable" ,
                "@operator-filter-registry/=lib/operator-filter-registry" ,
                "@solady/=lib/solady"
             ]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config